### ISSUE TITLE
"Fatal: std::bad_alloc" when converting onnx model to kmodel

### ISSUE THREAD

**Issue by annosoo** [kendryte/nncase#432] opened 2021-11-05 16:11 UTC
**Describe the bug**
I was trying to convert onnx model to kmodel with the lastest nncase tool. However, an error happened.
![图片](https://user-images.githubusercontent.com/37980541/140541369-128eb7d6-0026-411e-be58-d186a7db3774.png)

**To Reproduce**
here is my ncc command
` ./ncc -v compile -i onnx -t k210 model/model.onnx model/model_float.kmodel`

**Origin model and code**
here is my simple test model
[model.zip](https://github.com/kendryte/nncase/files/7487346/model.zip)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu20.04]
 - nncase version [e.g. v1.0.0.72ab6de]

**Additional context**
I have tried many nncase versions in master branch since v1.0.0.64a459e, all lead to the same error.

**Comment by zhen8838** [comment] 2021-11-06 04:47
```sh
❯ /Users/lisa/Documents/nncase/out/build/debug/bin/ncc -v compile -i onnx -t k210 tmp/model.onnx tmp/model_float.kmodel

nncase Command Line Tools 1.0.0-72ab6de7
Copyright 2019-2021 Canaan Inc.
1. Import graph...
2. Optimize target independent...
3. Optimize target dependent...
5. Optimize target dependent after quantization...
6. Optimize modules...
7.1. Merge module regions...
7.2. Optimize buffer fusion...
7.3. Optimize target dependent after buffer fusion...
8. Generate code...

SUMMARY
INPUTS
0       input   f32[1,1,28,28]
OUTPUTS
0       output  f32[1,10]

MEMORY USAGES
.input     3.06 KB      (3136 B)
.output   40.00 B       (40 B)
.data    120.00 B       (120 B)
MODEL     31.66 KB      (32416 B)
TOTAL     34.88 KB      (35712 B)
```

**Comment by zhen8838** [comment] 2021-11-06 04:48
Can't reproduce your issue.

**Comment by zhangyang2057** [comment] 2021-11-10 02:11
Duplicate of #396

**Closed** 2021-11-10 02:36 UTC
