### ISSUE TITLE
An issue about the "Build from source"

### ISSUE THREAD

**Issue by yc66542260** [kendryte/nncase#460] opened 2021-12-01 02:24 UTC
![image](https://user-images.githubusercontent.com/30710177/144160659-f1ebc9ae-4406-498a-99e9-954b76b9102b.png)

**Comment by yc66542260** [comment] 2021-12-01 02:32
When I tried to build nncase from the source, this issue always occured no matter which system I used (windows, linux or the docker). So do you have any suggestions that can help me to build nncase from the source successfully? Thanks!

**Comment by yc66542260** [comment] 2021-12-01 02:59
![image](https://user-images.githubusercontent.com/30710177/144164046-4d404e88-5a09-498f-9fd8-2cca6950df4c.png)

**Comment by yc66542260** [comment] 2021-12-01 03:21
I think those issues that occured respectively in docker and windows were different, but both of them had the common problem that none of them could find 'pybind11' in remotes. Then I checked the remotes.json in conan, there were two remotes: https://conan.sunnycase.moe and https://bintray.com/bincrafters/public-conan. But bintary is nolonger used.

**Comment by sunnycase** [comment] 2021-12-01 05:52
I think it's related to conan center's network issue.

**Comment by QiangZiBro** [comment] 2021-12-01 18:39
Hello, I downloaded the files on my mac computer successfully, I run `conan remote list`, giving the following output:
```
sunnycase: https://conan.sunnycase.moe [Verify SSL: True]
conancenter: https://center.conan.io [Verify SSL: True]
```
And in the docker image
```
WARN: Remotes registry file missing, creating default one in /root/.conan/remotes.json
conancenter: https://center.conan.io [Verify SSL: True]
conan-center: https://conan.bintray.com [Verify SSL: True]
```
Noticed that conan-center has been [deprecated](https://github.com/conan-io/conan/issues/7573#issuecomment-940083544), I removed `conan-center` and added `sunnycase` by:
```bash
# in docker container
conan remote remove conan-center
conan remote add sunnycase https://conan.sunnycase.moe
```

Then build command, still fails
```bash
rm -rf build && mkdir -p build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Debug
```
error msg:
```text
WARN: Remotes registry file missing, creating default one in /root/.conan/remotes.json
root@4f01ebca5619:/mnt# conan remote add sunnycase https://conan.sunnycase.moe
root@4f01ebca5619:/mnt# rm -rf build && mkdir -p build && cd build
root@4f01ebca5619:/mnt/build# cmake .. -DCMAKE_BUILD_TYPE=Debug
-- Found Git: /usr/bin/git (found version "2.25.1")
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Conan: checking conan executable
-- Conan: Found program /usr/local/bin/conan
a /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-- Conan: Version found Conan version 1.39.0

-- Conan: checking conan executable
-- Conan: Found program /usr/local/bin/conan
a /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-- Conan: Version found Conan version 1.39.0

-- Conan: Adding sunnycase remote repository (https://conan.sunnycase.moe) verify ssl (True)
-- Auto Cmake Conan Installation
-- Conan: Automatic detection of conan settings from cmake
-- Conan: compiler.cppstd was added as an argument. Not using the autodetected one.
-- Conan: Settings= -s;build_type=Debug;-s;compiler=gcc;-s;compiler.version=10;-s;compiler.libcxx=libstdc++11;-s;compiler.cppstd=20
-- Conan: checking conan executable
-- Conan: Found program /usr/local/bin/conan
a /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
-- Conan: Version found Conan version 1.39.0

-- Conan executing: /usr/local/bin/conan install /mnt/conanfile.py -s build_type=Debug -s compiler=gcc -s compiler.version=10 -s compiler.libcxx=libstdc++11 -s compiler.cppstd=20 -g=cmake --build=missing -o=runtime=False -o=tests=False -o=python=True -o=openmp=True -o=vulkan_runtime=False -o=halide=True
Auto detecting your dev setup to initialize the default profile (/root/.conan/profiles/default)
CC and CXX: /usr/bin/cc, /usr/bin/c++
Default settings
	os=Linux
	os_build=Linux
	arch=x86_64
	arch_build=x86_64
	build_type=Release
*** You can change them in /root/.conan/profiles/default ***
*** Or override with -s compiler='other' -s ...s***


Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Debug
compiler=gcc
compiler.cppstd=20
compiler.libcxx=libstdc++11
compiler.version=10
os=Linux
os_build=Linux
[options]
halide=True
openmp=True
python=True
runtime=False
tests=False
vulkan_runtime=False
[build_requires]
[env]

gsl-lite/0.37.0: Not found in local cache, looking in remotes...
gsl-lite/0.37.0: Trying with 'sunnycase'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
gsl-lite/0.37.0: Downloaded recipe revision 0
mpark-variant/1.4.0: Not found in local cache, looking in remotes...
mpark-variant/1.4.0: Trying with 'sunnycase'...
Downloading conanmanifest.txt
Downloading conanfile.py
Downloading conan_export.tgz
mpark-variant/1.4.0: Downloaded recipe revision 0
hkg/0.0.1: Not found in local cache, looking in remotes...
hkg/0.0.1: Trying with 'sunnycase'...
Downloading conanmanifest.txt
Downloading conanfile.py
hkg/0.0.1: Downloaded recipe revision 0
pybind11/2.6.1: Not found in local cache, looking in remotes...
pybind11/2.6.1: Trying with 'sunnycase'...
pybind11/2.6.1: Trying with 'conancenter'...
ERROR: Not able to automatically detect '/usr/bin/cc' version
ERROR: Unable to find a working compiler
ERROR: Failed requirement 'pybind11/2.6.1' from 'conanfile.py'
ERROR: HTTPSConnectionPool(host='center.conan.io', port=443): Max retries exceeded with url: /v1/ping (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)')))

Unable to connect to conancenter=https://center.conan.io
1. Make sure the remote is reachable or,
2. Disable it by using conan remote disable,
Then try again.
CMake Error at cmake/conan.cmake:522 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:759 (old_conan_cmake_install)
  CMakeLists.txt:60 (conan_cmake_run)


-- Configuring incomplete, errors occurred!
See also "/mnt/build/CMakeFiles/CMakeOutput.log".
```

**Comment by QiangZiBro** [comment] 2021-12-01 18:51
Finally I upgraded `conan` from 1.39 to 1.42, then the problem solved
```
pip uninstall conan -y
pip install conan
```

**Comment by zhangyang2057** [comment] 2021-12-02 06:47
I added "conan config install https://github.com/conan-io/conanclientcert.git" command in the nncase docker image just now and pushed it to latest. Now it can build nncase from source successfully.

You can docker pull registry.cn-hangzhou.aliyuncs.com/kendryte/nncase:latest and try aggin.

**Comment by yc66542260** [comment] 2021-12-02 09:17
> 

Amazing! It works~ But I can only the the command "cmake .. -DCMAKE_BUILD_TYPE=Release" to build, with "cmake .. -DCMAKE_BUILD_TYPE=Debug", it still fails...

**Comment by yc66542260** [comment] 2021-12-02 09:18
@QiangZiBro Amazing! It works~ But I can only the the command "cmake .. -DCMAKE_BUILD_TYPE=Release" to build, with "cmake .. -DCMAKE_BUILD_TYPE=Debug", it still fails...

**Comment by yc66542260** [comment] 2021-12-02 10:30
@zhangyang2057 cool, I will try it later, thanks~

**Comment by zhangyang2057** [comment] 2021-12-02 10:46
For Debug version,  the latest docker image may raise error, such as
```
libjpeg/9d: Configuring sources in /root/.conan/data/libjpeg/9d/_/_/source
Waiting 5 seconds to retry...
WARN: xtensor/0.21.5: requirement nlohmann_json/3.7.3 overridden by your conanfile to nlohmann_json/3.9.1 
WARN: spdlog/1.8.2: requirement fmt/7.1.2 overridden by your conanfile to fmt/7.1.3 
gsl-lite/0.37.0: WARN: This conanfile has no build step
ERROR: Error 406 downloading file http://ijg.org/files/jpegsrc.v9d.tar.gz
ERROR: libjpeg/9d: Error in source() method, line 41
	tools.get(**self.conan_data["sources"][self.version])
	ConanException: Error 406 downloading file http://ijg.org/files/jpegsrc.v9d.tar.gz
CMake Error at cmake/conan.cmake:522 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  cmake/conan.cmake:759 (old_conan_cmake_install)
  CMakeLists.txt:60 (conan_cmake_run)
```

Go on building nncase until you build nncase successfully.

At last, save ~/.conan/data/ to your disk.  You can reuse it again by copying it back to ~/.conan/data when buliding nncase next time.

**Comment by zhangyang2057** [comment] 2021-12-10 01:30
@yc66542260 Is there any update?

**Comment by zhangyang2057** [comment] 2021-12-10 08:33
The latest issue was caused by the network about conan. Keep on building nncase can fix the issue.
No reply for a long time. 
Close it.

**Closed by zhangyang2057** 2021-12-10 08:33 UTC
